apiVersion: apps/v1
kind: Deployment
metadata:
  name: journal-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journal-app
  template:
    metadata:
      labels:
        app: journal-app
    spec:
      containers:
        - name: journal-app
          image: ltcregistry.azurecr.io/journal-app:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: journal-config
            - secretRef:
                name: journal-secrets
